In [62]:

import pandas as pd
import numpy as np

In [63]:
data=pd.read_csv('sentiment.csv',encoding = "ISO-8859-1")

In [64]:

data1=pd.DataFrame(columns=['target','tweets'])
data1

Empty DataFrame
Columns: [target, tweets]
Index: []

In [65]:
data.head()

target                                             tweets
0    -1.0  when modi promised “minimum government maxim...
1     0.0  talk all the nonsense and continue all the dra...
2     1.0  what did just say vote for modi  welcome bjp t...
3     1.0  asking his supporters prefix chowkidar their n...
4     1.0  answer who among these the most powerful world...

In [66]:
data=data.dropna()

In [67]:

x=data['tweets']
y=data['target']

In [68]:
x.shape


(162969,)

In [69]:
y.shape


(162969,)

In [70]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [71]:
voc_size=5000


In [72]:
messages = data.copy()

In [73]:
import nltk
import re
from nltk.corpus import stopwords

In [74]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['tweets'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148


KeyError: 148

In [ ]:
corpus


In [75]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[1949,
  163,
  3593,
  3378,
  3339,
  3378,
  58,
  3632,
  3262,
  4295,
  979,
  462,
  472,
  3382,
  2488,
  3563,
  462,
  2812,
  3808,
  4246,
  1371],
 [1004, 4700, 3955, 1114, 2825, 1949],
 [3184, 2825, 1949, 1231, 4139, 424, 2873, 3601, 1844, 1949, 1882, 1949, 1937],
 [3520,
  3811,
  1936,
  3213,
  704,
  1949,
  4110,
  4410,
  2011,
  4975,
  2178,
  2668,
  3987,
  4065,
  4700,
  4560,
  1323,
  3609,
  3213],
 [4325, 3178, 1141, 164, 1839, 2283, 1975, 3005, 1949, 1262],
 [1059, 1761, 2887, 853, 2204, 1363],
 [2049, 1125, 1614, 145, 158, 2121, 942, 4194, 1949, 1232],
 [3609, 3239, 1756, 1202, 1949, 2526, 162, 3879, 155],
 [415,
  4115,
  789,
  3366,
  890,
  226,
  1418,
  4163,
  2844,
  1949,
  4800,
  678,
  4115,
  1950,
  1449,
  1842,
  676,
  4163,
  408,
  439,
  1670],
 [3113, 2894, 1949],
 [226,
  1202,
  3300,
  2947,
  2716,
  4410,
  2945,
  1922,
  3356,
  3178,
  1633,
  3062,
  2633,
  2971,
  3184,
  3434,
  3793,
  3879,
  3356,
  1202,
  1987,
  2

In [76]:
sent_length=2
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[4246 1371]
 [2825 1949]
 [1949 1937]
 [3609 3213]
 [1949 1262]
 [2204 1363]
 [1949 1232]
 [3879  155]
 [ 439 1670]
 [2894 1949]
 [1949 1651]
 [4783 4690]
 [1949 1592]
 [ 193 1844]
 [3811 1844]
 [4139 1569]
 [4578 4295]
 [2711 4115]
 [4764 4887]
 [3397 3283]
 [ 226 4090]
 [4620 2283]
 [2332 4070]
 [4180   48]
 [3052 1474]
 [ 956  789]
 [3643 2347]
 [1004 2555]
 [ 714  995]
 [3720 1456]
 [ 735 3359]
 [2711 4115]
 [ 789 3883]
 [1632  787]
 [1949 3239]
 [   0 1949]
 [1287 3359]
 [2305 3382]
 [3972 2825]
 [ 846 2909]
 [ 321 2059]
 [3629 3839]
 [1171  789]
 [4695  923]
 [1133 2590]
 [2825 4406]
 [2054 1646]
 [2394 1844]
 [ 789 3603]
 [ 359  801]
 [2791 4115]
 [1949 4812]
 [2013 4729]
 [1251 4224]
 [4796 1526]
 [4788 3916]
 [1949   71]
 [4657 4364]
 [2753 1782]
 [4299 4139]
 [ 989 4343]
 [ 704  393]
 [2279 2839]
 [2054 1646]
 [4139  201]
 [1698 2248]
 [4090 3359]
 [3649 2678]
 [1595 1540]
 [4194 1949]
 [4626 3943]
 [1152 4222]
 [3609 1141]
 [4578 2354]
 [4812 1747]
 [1360  385]
 [3178 1961]

In [77]:
embedded_docs[0]


array([4246, 1371])

In [78]:

embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 2, 40)             200000    
_________________________________________________________________
lstm_5 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [79]:
len(embedded_docs),y.shape


(148, (162969,))

In [84]:
import numpy as np
X_final=np.array(embedded_docs)
y_semifinal=np.array(y)
y_final = y_semifinal[:148]

In [85]:
X_final.shape,y_final.shape

((148, 2), (148,))

In [88]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [89]:
X_final

array([[4246, 1371],
       [2825, 1949],
       [1949, 1937],
       [3609, 3213],
       [1949, 1262],
       [2204, 1363],
       [1949, 1232],
       [3879,  155],
       [ 439, 1670],
       [2894, 1949],
       [1949, 1651],
       [4783, 4690],
       [1949, 1592],
       [ 193, 1844],
       [3811, 1844],
       [4139, 1569],
       [4578, 4295],
       [2711, 4115],
       [4764, 4887],
       [3397, 3283],
       [ 226, 4090],
       [4620, 2283],
       [2332, 4070],
       [4180,   48],
       [3052, 1474],
       [ 956,  789],
       [3643, 2347],
       [1004, 2555],
       [ 714,  995],
       [3720, 1456],
       [ 735, 3359],
       [2711, 4115],
       [ 789, 3883],
       [1632,  787],
       [1949, 3239],
       [   0, 1949],
       [1287, 3359],
       [2305, 3382],
       [3972, 2825],
       [ 846, 2909],
       [ 321, 2059],
       [3629, 3839],
       [1171,  789],
       [4695,  923],
       [1133, 2590],
       [2825, 4406],
       [2054, 1646],
       [2394,

In [90]:
from keras.callbacks import ModelCheckpoint


In [91]:
import os


In [92]:
checkpoint_path= "training_1/cp.ckpt"
checkpoint_dir= os.path.dirname(checkpoint_path)

In [95]:
import tensorflow
cp_callback=tensorflow.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,save_weights_only=True,verbose=1)


In [96]:
p=model.fit(X_train,y_train,validation_data=(X_test,y_test),callbacks=[cp_callback],epochs=1,batch_size=64)


2/2 [==============================] - 4s 795ms/step - loss: 0.6922 - accuracy: 0.3535 - val_loss: 0.6881 - val_accuracy: 0.4694

Epoch 00001: saving model to training_1\cp.ckpt


In [97]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [111]:
# y_pred=model.predict_classes(X_test)
y_pred = model.predict(X_test)


In [112]:
from sklearn.metrics import confusion_matrix


In [114]:
from scipy import stats 
import numpy as np

#taking the most frequent element from the predicted list
y_pred_list = [int(stats.mode(arr)[0]) for arr in y_pred.tolist()] #convert to list

y_pred_array = np.array(y_pred_list)  #convert to 1D with same shape of y_test

print(y_pred_array.shape)

print(y_pred_array)

matrix = confusion_matrix(y_test, y_pred_array)

(49,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0]


In [116]:
y_pred.shape


(49, 1)

In [117]:
import pickle


In [118]:
from tensorflow.keras.models import save_model, load_model


In [119]:

filepath= './saved_model'
save_model(model,filepath)

INFO:tensorflow:Assets written to: ./saved_model\assets


INFO:tensorflow:Assets written to: ./saved_model\assets


In [120]:
y_pred


array([[0.50097966],
       [0.4959919 ],
       [0.49968764],
       [0.49896997],
       [0.49978715],
       [0.495663  ],
       [0.49832758],
       [0.4997675 ],
       [0.5024118 ],
       [0.49573484],
       [0.49912617],
       [0.49834487],
       [0.4987512 ],
       [0.49814698],
       [0.49756867],
       [0.4993129 ],
       [0.5001367 ],
       [0.49663138],
       [0.50343287],
       [0.4994921 ],
       [0.4988559 ],
       [0.49931693],
       [0.50087786],
       [0.50109386],
       [0.49943453],
       [0.5033694 ],
       [0.5022548 ],
       [0.50083303],
       [0.5027476 ],
       [0.49921402],
       [0.49933186],
       [0.50200146],
       [0.4982054 ],
       [0.49954885],
       [0.4980645 ],
       [0.4955983 ],
       [0.49662387],
       [0.5004792 ],
       [0.49968573],
       [0.5005049 ],
       [0.49595606],
       [0.5002863 ],
       [0.5035068 ],
       [0.4970732 ],
       [0.49589485],
       [0.50051224],
       [0.5020013 ],
       [0.498